BEGIN;

CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
	login VARCHAR(100) NOT NULL UNIQUE,
	password VARCHAR(100) NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS order_status (
    id SMALLSERIAL PRIMARY KEY,
	name VARCHAR(30) NOT NULL UNIQUE
);

INSERT INTO order_status (name)
VALUES
    ('NEW'),
	('PROCESSING'),
	('INVALID'),
	('PROCESSED')
ON CONFLICT DO NOTHING;

CREATE TABLE IF NOT EXISTS orders (
    id SERIAL PRIMARY KEY,
	user_id INTEGER NOT NULL REFERENCES users(id),
	status_id SMALLINT NOT NULL REFERENCES order_status(id) DEFAULT 1,
	number VARCHAR(30) NOT NULL UNIQUE,
	accrual NUMERIC(9, 2) NOT NULL DEFAULT 0,
	uploaded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS bonus_accounts (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL UNIQUE,
    balance NUMERIC(9, 2) NOT NULL DEFAULT 0,
    wathdraw NUMERIC(9, 2) NOT NULL DEFAULT 0,
    last_update TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS bonus_transactions (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL,
    order_number VARCHAR(30) NOT NULL,
    transaction_type VARCHAR(1) NOT NULL,
    transaction_amount NUMERIC(9, 2) NOT NULL,
    processed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

END;
