CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
	login VARCHAR(100) NOT NULL UNIQUE,
	password VARCHAR(100) NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS order_status (
    id SMALLSERIAL PRIMARY KEY,
	name VARCHAR(30) NOT NULL UNIQUE
);

INSERT INTO order_status (name)
VALUES
    ('NEW'),
	('PROCESSING'),
	('INVALID'),
	('PROCESSED')
ON CONFLICT DO NOTHING;

CREATE TABLE IF NOT EXISTS orders_bonuses (
    id SERIAL PRIMARY KEY,
	number BIGINT NOT NULL UNIQUE,
	accrual NUMERIC(9, 2) NULL,
	status_id SMALLINT REFERENCES order_status DEFAULT 1,
	uploaded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
