BEGIN;

CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
	login VARCHAR(100) NOT NULL UNIQUE,
	password VARCHAR(100) NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS orders (
    id SERIAL PRIMARY KEY,
	user_id INTEGER NOT NULL REFERENCES users(id),
	number VARCHAR(30) NOT NULL UNIQUE,
	status VARCHAR(30) NOT NULL DEFAULT 'NEW',
	accrual REAL NOT NULL DEFAULT 0,
	uploaded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_update TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS bonus_accounts (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL UNIQUE REFERENCES users(id),
    balance REAL NOT NULL DEFAULT 0,
    withdraw REAL NOT NULL DEFAULT 0,
    last_update TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS bonus_transactions (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id),
    order_number VARCHAR(30) NOT NULL,
    transaction_type VARCHAR(1) NOT NULL,
    transaction_amount REAL NOT NULL,
    processed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

END;
