name: go vet test

on:
  pull_request:
  push:
    branches:
      - master
      - main

jobs:
  statictest:
    runs-on: ubuntu-latest
    container: golang:1.24.1
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Checkout statictest code
        uses: actions/checkout@v4
        with:
          repository: Yandex-Practicum/go-autotests
          sparse-checkout: |
            cmd/statictest
            go.mod
            go.sum
          sparse-checkout-cone-mode: false
          path: statictest
      
      - name: list files
        run: |
          ls -la
          ls -laR statictest
      
      - name: Prepare statictest binary
        run: | 
          cd statictest && go build -buildvcs=false -o statictest

      # - name: Setup autotest binary
      #   run: |
      #     chmod -R +x $GITHUB_WORKSPACE/.tools/statictest
      #     mv $GITHUB_WORKSPACE/.tools/statictest /usr/local/bin/statictest

      
      # - name: Run statictest
      #   run: |
      #     go vet -vettool=$(which statictest) ./... 
